### ISSUE TITLE
Deploy controller using Tmux

### ISSUE THREAD

**Issue by JWTappert** [osu-cascades/dio-controllers#20]
tmux allows for terminal multiplexing and will allow us to run our controller code and detach the session from our ssh so that it continues to run.
[TMUX](https://github.com/tmux/tmux/wiki)

**Comment by MakeilaLundy** [comment]
-get ip of rasbperry pi using `$ ifconfig`  first inet address is your ip adress
-enable ssh on raspberry pi with  sudoraspi-config
-ssh into raspberry pi ( `$ ssh user@ipaddress `)(on your computer )
-enter password for your rp3
-  run `$ sudo apt-get update`
-run `$ sudo apt-get install tmux`
- you now have it installed. to run tmux 
-run `$ tmux `
** To detach a session **
Ctrl-b d

** To reattch a session **
`$ tmux attach -t  [session name]`
cd to you project directory on your pi from your computer. 
** to List sessiosn running **
`$ tmux List-Sessions `

**Comment by MakeilaLundy** [comment]
:fire:
