### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by JWTappert** [osu-cascades/dio-controllers#5]

**Comment by JWTappert** [comment]
I want to add detailed pictures of the wiring because that part was a big pain in the butt

**Comment by MakeilaLundy** [comment]
FRitzing?

**Comment by JWTappert** [comment]
@MakeilaLundy oh maybe, i was thinking like actual pictures lol

**Comment by MakeilaLundy** [comment]
Yeah either one! FRitzing would probably be more clean looking
